<template>
  <div class="vp-raw grid gap-2">
    <fwb-progress
      label="Default"
      :progress="12.5"
      value-position="inside"
      show-value
      size="lg"
    />
    <fwb-progress
      color="dark"
      label="Dark"
      :progress="25"
      value-position="inside"
      show-value
      size="lg"
    />
    <fwb-progress
      color="blue"
      label="Blue"
      :progress="37.5"
      value-position="inside"
      show-value
      size="lg"
    />
    <fwb-progress
      color="red"
      label="Red"
      :progress="50"
      value-position="inside"
      show-value
      size="lg"
    />
    <fwb-progress
      color="green"
      label="Green"
      :progress="62.5"
      value-position="inside"
      show-value
      size="lg"
    />
    <fwb-progress
      color="yellow"
      label="Yellow"
      :progress="75"
      value-position="inside"
      show-value
      size="lg"
    />
    <fwb-progress
      color="purple"
      label="Purple"
      :progress="87.5"
      value-position="inside"
      show-value
      size="lg"
    />
    <fwb-progress
      color="pink"
      label="Pink"
      :progress="100"
      value-position="inside"
      show-value
      size="lg"
    />
  </div>
</template>

<script lang="ts" setup>
import { FwbProgress } from '../../../../src/index'
</script>
